#!/bin/bash
echo "=> Building petclinic"
docker run -i --rm --name my-maven-project -v "$(pwd)":/usr/src/mymaven -w /usr/src/mymaven maven:3.3-jdk-8 mvn clean install

echo "=> Pulling in cached image"
docker pull tjwatson/spring-petclinic || true

echo "=> Building petclinic Docker image"
docker build --pull --cache-from tjwatson/spring-petclinic --tag tjwatson/spring-petclinic .

